on: [push]

jobs:
  getdata:
    runs-on: ubuntu-latest
    name: Get code context
    # Map a step output to a job output
    outputs:
      result: ${{ steps.watermelon.outputs.ghdata }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Watermelon context
        id: watermelon
        uses: ./
  writedata:
    runs-on: ubuntu-latest
    needs: getdata
    name: Write a comment
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: ${{ steps.watermelon.outputs.result }}
