on: [push]

jobs:
  getdata:
    runs-on: ubuntu-latest
    name: Get code context
    # Map a step output to a job output
    outputs:
      result: ${{ steps.watermelon.outputs.textToWrite }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Watermelon context
        id: watermelon
        uses: ./
  writedata:
    runs-on: ubuntu-latest
    needs: getdata
    name: Write a comment
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event..pull_request.number }}
          body: ${{ needs.getdata.outputs.result }}
